name: Using GitHub Secrets

on: [push]

jobs:
  create-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "TEST_SECRETS=${{ secrets.TEST_SECRETS }}" >> .env
          echo "File content:"
          cat .env
          echo "File size:"
          ls -l .env

      - name: Debug environment
        run: |
          echo "Environment variables:"
          env
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la