name: Using GitHub Secrets

on: [push]

jobs:
    create-env-file-mid:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Create and print .env file
              run: |
                echo ${{secrets.TEST_SECRETS}} > .env
                base64 .env

            - name: Test printing your secret (Remove this step in production)
              run: base64 .env
