name: Using GitHub Secrets

on: [push]

jobs:
    create-env-file-mid:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Print base64 encoded TEST_SECRETS
              run: echo "${{ secrets.TEST_SECRETS }}" | base64

            - name: Create .env file
              run: |
                  touch .env
                  echo "${{ secrets.TEST_SECRETS }}" >> .env

            - name: Test printing your secret (Remove this step in production)
              run: cat .env